### PR TITLE
[Feature] API and UI for User Administration

### PR DESCRIPTION
**Pull request by mike1e**
[DLO1-190](https://dlohaiti.atlassian.net/browse/DLO1-190)

A react app for SEMA User Administration with routing for user api endpoints.

### CODE REVIEW

**Review by meaudotme — CHANGES_REQUESTED** [review]
That's a great start! Just one thing, the dashboard client is already running on port 3000 in dev mode, how about you set the admin client to run on port 3002 for example?

**Comment by mike1e** [comment]
@R4meau changes made in the package.json file 095125d

**Review by meaudotme — APPROVED** [review]

**Review by FredOleary — APPROVED** [review]
OK by me

**Comment by meaudotme** [comment]
@mike1e Btw, I really like the little detail between brackets you add to your commit messages and the PR title. Haha, stealing this style ;) Thanks.

**Pull request merged**
